### ISSUE TITLE
Test suite fails (with newest Data::Object::Role::Proxyable?)

### ISSUE THREAD

**Issue by eserte** [iamalnewkirk/doodle#19]
The test suite started to fail on my smokers. A sample fail report: http://www.cpantesters.org/cpan/report/237a99a4-560f-11ea-991f-f84f1f24ea8f

Experiments suggest that the failure happens if the newest Data::Object::Role::Proxyable is installed.

**Comment by iamalnewkirk** [comment]
@eserte Thanks. This will be fixed shortly in https://github.com/iamalnewkirk/data-object-role-proxyable/issues/4.
