### ISSUE TITLE
Question: You thinking about making an active record orm with Data::Object? :D

### ISSUE THREAD

**Issue by matthewlenz** [iamalnewkirk/doodle#3]
I've been following Data::Object for a long time and the first thing that came to mind was "Man, you could use this to make an awesome Active Record ORM." :D

**Comment by iamalnewkirk** [comment]
Hey @matthewlenz, no, not really. I really like DBIC, speaking as someone who has used both extensively. Please let me know if you have any interest in contributing!

**Comment by matthewlenz** [comment]
Which other ORMs have you tried that you didn't like as much as DBIC out of curiosity?

**Comment by iamalnewkirk** [comment]
I've used ActiveRecord, Eloquent, Ecto, Knex.js and Bookshelf.js. The thing DBIC supports that the other do not is complex querying without resorting to platform specific SQL statements.
